name: echo

on:
  workflow_dispatch:

  push:

permissions:
  contents: read
  id-token: write

env:
  sstun: 'stunserver.stunprotocol.org'

jobs:
  echo:
    name: Test disk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Environment
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install golang
          cd /opt && git clone https://github.com/gomarkdown/mdtohtml.git && cd mdtohtml && go install
          echo 'export PATH="$HOME/go/bin:$PATH"' >> "$HOME/.profile"
          echo 'export PATH="$HOME/go/bin:$PATH"' >> "$HOME/.bashrc"

      - name: Test
        shell: bash
        run: |
          cat "$HOME/.bashrc"
          mdtohtml -h

