name: echo

on:
  workflow_dispatch:

  push:

permissions:
  contents: read
  id-token: write

env:
  sstun: 'stunserver.stunprotocol.org'

jobs:
  echo:
    name: Test ${{ matrix.target[0] }}-${{ matrix.target[1] }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - ['ipq806x', 'generic']
          - ['ath79', 'nand']
          - ['x86', '64']
        include:
          - target: ['ath79', 'nand']
            profile: netgear_wndr4300
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate full target name
        env:
          TARGET: ${{ format('{0}-{1}', matrix.target[0], matrix.target[1]) }}
        run: |
          echo "Full target name is $TARGET"
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: Test
        env:
          ARCH: ${{ format('{0}-{1}', env.TARGET, matrix.profile) }}
        run: |
          echo $ARCH
