name: echo

on:
  workflow_dispatch:

  push:

permissions:
  contents: read
  id-token: write

env:
  sstun: 'stunserver.stunprotocol.org'

jobs:
  echo:
    name: Test disk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lsblk
        run: |
          lsblk

      - name: df
        run: |
          df -h

