name: echo

on:
  workflow_dispatch:

  push:

permissions:
  contents: read
  id-token: write

env:
  sstun: 'stunserver.stunprotocol.org'

jobs:
  echo:
    name: Test IP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get IPv4 Addr
        run: |
          dig +short myip.opendns.com @resolver1.opendns.com

      - name: Get IPv6 Addr
        run: |
          dig +short -6 myip.opendns.com aaaa @resolver1.ipv6-sandbox.opendns.com

